//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelado
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asistencia
    {
        public int Id { get; set; }
        public bool estado { get; set; }
        public string fecha_asistencia { get; set; }
        public int MatriculaId { get; set; }
    
        public virtual Matricula Matricula { get; set; }
    }
}
