//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelado
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstudiantePadre
    {
        public int Id { get; set; }
        public int EstudianteId { get; set; }
        public int PadreId { get; set; }
    
        public virtual Estudiante Estudiante { get; set; }
        public virtual Padre Padre { get; set; }
    }
}
