//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelado
{
    using System;
    using System.Collections.Generic;
    
    public partial class Horario
    {
        public Horario()
        {
            this.HorarioMatricula = new HashSet<HorarioMatricula>();
        }
    
        public int Id { get; set; }
        public string hora_incio { get; set; }
        public string hora_fin { get; set; }
    
        public virtual ICollection<HorarioMatricula> HorarioMatricula { get; set; }
    }
}
