//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelado
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfesorAsignatura
    {
        public ProfesorAsignatura()
        {
            this.Matricula = new HashSet<Matricula>();
        }
    
        public int Id { get; set; }
        public int ProfesorId { get; set; }
        public int AsignaturaId { get; set; }
    
        public virtual Profesor Profesor { get; set; }
        public virtual Asignatura Asignatura { get; set; }
        public virtual ICollection<Matricula> Matricula { get; set; }
    }
}
