//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelado
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.Estudiante = new HashSet<Estudiante>();
            this.Profesor = new HashSet<Profesor>();
            this.Padre = new HashSet<Padre>();
            this.Admin = new HashSet<Admin>();
            this.Notificacion = new HashSet<Notificacion>();
        }
    
        public int Id { get; set; }
        public string nombreusuario { get; set; }
        public string contrasena { get; set; }
        public System.DateTime fecha_registro { get; set; }
    
        public virtual ICollection<Estudiante> Estudiante { get; set; }
        public virtual ICollection<Profesor> Profesor { get; set; }
        public virtual ICollection<Padre> Padre { get; set; }
        public virtual ICollection<Admin> Admin { get; set; }
        public virtual ICollection<Notificacion> Notificacion { get; set; }
    }
}
